name: Build A11ZeroAuto
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Theos
        uses: Randomblock1/theos-action@v1
      - name: Build Package
        run: make package THEOS_PACKAGE_SCHEME=rootless
      - name: Upload Artifact
        uses: actions/abstract/upload-artifact@v3
        with:
          name: A11ZeroAuto_Deb
          path: packages/*.deb
